# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'job_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11job_service.proto\x12\x08mobility\"1\n\rScrapeRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0f\n\x07keyword\x18\x02 \x01(\t\"-\n\x0eScrapeResponse\x12\x1b\n\x04jobs\x18\x01 \x03(\x0b\x32\r.mobility.Job\"q\n\x03Job\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x1a\n\x12sponsorship_status\x18\x04 \x01(\t\x12\x0f\n\x07summary\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t2U\n\nJobService\x12G\n\x10ScrapeAndAnalyze\x12\x17.mobility.ScrapeRequest\x1a\x18.mobility.ScrapeResponse\"\x00\x42\'\n\x12\x63om.mobility.protoB\x0fJobServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.mobility.protoB\017JobServiceProtoP\001'
  _globals['_SCRAPEREQUEST']._serialized_start=31
  _globals['_SCRAPEREQUEST']._serialized_end=80
  _globals['_SCRAPERESPONSE']._serialized_start=82
  _globals['_SCRAPERESPONSE']._serialized_end=127
  _globals['_JOB']._serialized_start=129
  _globals['_JOB']._serialized_end=242
  _globals['_JOBSERVICE']._serialized_start=244
  _globals['_JOBSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
