// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: job_service.proto
// Protobuf Java Version: 4.33.2

package com.mobility.proto;

@com.google.protobuf.Generated
public interface JobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mobility.Job)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  java.lang.String getCompany();
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <pre>
   * e.g., "Confirmed", "Likely", "None"
   * </pre>
   *
   * <code>string sponsorship_status = 4;</code>
   * @return The sponsorshipStatus.
   */
  java.lang.String getSponsorshipStatus();
  /**
   * <pre>
   * e.g., "Confirmed", "Likely", "None"
   * </pre>
   *
   * <code>string sponsorship_status = 4;</code>
   * @return The bytes for sponsorshipStatus.
   */
  com.google.protobuf.ByteString
      getSponsorshipStatusBytes();

  /**
   * <code>string summary = 5;</code>
   * @return The summary.
   */
  java.lang.String getSummary();
  /**
   * <code>string summary = 5;</code>
   * @return The bytes for summary.
   */
  com.google.protobuf.ByteString
      getSummaryBytes();

  /**
   * <code>string url = 6;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 6;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
