// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: job_service.proto
// Protobuf Java Version: 4.33.2

package com.mobility.proto;

@com.google.protobuf.Generated
public final class JobServiceProto extends com.google.protobuf.GeneratedFile {
  private JobServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "JobServiceProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobility_ScrapeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobility_ScrapeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobility_ScrapeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobility_ScrapeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mobility_Job_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobility_Job_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021job_service.proto\022\010mobility\"1\n\rScrapeR" +
      "equest\022\017\n\007country\030\001 \001(\t\022\017\n\007keyword\030\002 \001(\t" +
      "\"-\n\016ScrapeResponse\022\033\n\004jobs\030\001 \003(\0132\r.mobil" +
      "ity.Job\"q\n\003Job\022\r\n\005title\030\001 \001(\t\022\017\n\007company" +
      "\030\002 \001(\t\022\020\n\010location\030\003 \001(\t\022\032\n\022sponsorship_" +
      "status\030\004 \001(\t\022\017\n\007summary\030\005 \001(\t\022\013\n\003url\030\006 \001" +
      "(\t2U\n\nJobService\022G\n\020ScrapeAndAnalyze\022\027.m" +
      "obility.ScrapeRequest\032\030.mobility.ScrapeR" +
      "esponse\"\000B\'\n\022com.mobility.protoB\017JobServ" +
      "iceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mobility_ScrapeRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mobility_ScrapeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mobility_ScrapeRequest_descriptor,
        new java.lang.String[] { "Country", "Keyword", });
    internal_static_mobility_ScrapeResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_mobility_ScrapeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mobility_ScrapeResponse_descriptor,
        new java.lang.String[] { "Jobs", });
    internal_static_mobility_Job_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_mobility_Job_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mobility_Job_descriptor,
        new java.lang.String[] { "Title", "Company", "Location", "SponsorshipStatus", "Summary", "Url", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
