// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: job_service.proto
// Protobuf Java Version: 4.33.2

package com.mobility.proto;

@com.google.protobuf.Generated
public interface ScrapeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mobility.ScrapeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * e.g., "Software Engineer"
   * </pre>
   *
   * <code>string keyword = 2;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <pre>
   * e.g., "Software Engineer"
   * </pre>
   *
   * <code>string keyword = 2;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();
}
