// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: job_service.proto
// Protobuf Java Version: 4.33.2

package com.mobility.proto;

@com.google.protobuf.Generated
public interface ScrapeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mobility.ScrapeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mobility.Job jobs = 1;</code>
   */
  java.util.List<com.mobility.proto.Job> 
      getJobsList();
  /**
   * <code>repeated .mobility.Job jobs = 1;</code>
   */
  com.mobility.proto.Job getJobs(int index);
  /**
   * <code>repeated .mobility.Job jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <code>repeated .mobility.Job jobs = 1;</code>
   */
  java.util.List<? extends com.mobility.proto.JobOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <code>repeated .mobility.Job jobs = 1;</code>
   */
  com.mobility.proto.JobOrBuilder getJobsOrBuilder(
      int index);
}
